title: Hello, world! I'm Peter White
description: I'm a backend developer from London with an interest in Python
permalink: ':title/'
domain: "petergswhite.github.io"
baseurl: "https://petergswhite.github.io" 
url: "https://github.com/PeterGSWhite/PeterGSWhite.github.io/"
# site-twitter:

# Author Settings
author: Peter White
author-img: peter-white.png
about-author: I'm a backend developer from London with an interest in Python
# social-twitter: 
# social-facebook: 
social-github: PeterGSWhite
# social-linkedin:
social-email: petergswhite@gmail.com

# Disqus
# discus-identifier:

# Tracker
# analytics:

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
